### PR TITLE
Update readme and fix build

### PR DESCRIPTION
**Pull request by dreampiggy**
Update readme and modify fork URLs to this original repo

Maybe we should also update release page and the official site((http://isparta.github.io) to put the latest release binary

### CODE REVIEW

**Comment by dreampiggy** [comment]
@hahnzhu I change my fork readme url to this original repo. And after this merged, maybe we should add a git tag `2.0` and upload that release binary from my fork [release page](https://github.com/dreampiggy/iSparta/releases) to this repo and also that official site((http://isparta.github.io) ?

**Comment by dreampiggy** [comment]
Sorry for that. I found my fork's macOS release zip does not contain that `apngopt` command binary. So the PNG to APNG convertor output files may be larger than expect. Therefore, I use the v1.4 `apngopt` and please reupload the latest zip release again 😢 


I also find that I comment those `checkVersion` and `postData` code in `iSparta.js` because the server(`http://zhijie.me/iSparta/data.php`) is down. If you need these, you can add back.

**Comment by hkz404** [comment]
@dreampiggy yes http://zhijie.me/iSparta/data.php is down, remove it will be ok. I and jeakey have no much time on this project, so you're free to make it better,  i will review your improvement when i'm available.

**Comment by hkz404** [comment]
@dreampiggy  i have invite you as our organization member, if you have time please help us about this:

> Maybe we should also update release page and the official site((http://isparta.github.io) to put the latest release binary

**Comment by dreampiggy** [comment]
@hahnzhu Thanks. I will try to update that official site and provide the release and new feature about apng to animated webp if I have time. 😄

**Pull request merged**
