### PR TITLE
Add APNG to Animated WebP convertor and update libwebp

### PR DESCRIPTION
**Pull request by dreampiggy**
Add APNG to Animated WebP convertor and update libwebp

1. Add APNG to Animated WebP GUI part, include html entry , css and js
2. Update libwebp to 6.0 and just place cwebp and webpmux for convertor usage
3. Add apng2webp_apngopt and apngdisraw cli
4. Delete unused resources
5. Fix some experience issues and make the descriptions more universal
6. Format indent with Tabs in main.html

### CODE REVIEW

**Comment by dreampiggy** [comment]
I hope that the author: @jeakey and contributor @hahnzhu who are interested in this project can review this PR. Thanks.

**Comment by hkz404** [comment]
thx bro!

**Comment by dreampiggy** [comment]
@hahnzhu I'm so exicited that this project is still maintained... These commit add some description that only used in my fork(I firstly fork this repo and commit for pull request, but later I think this is no long maintained and commit some more changes to my fork repo `master` branch but forget that this will also be in the pull request to this repo)

Could you please add me to the collaborators and change these commit, including:

1. README.md - change url to this repo but not my fork repo
2. Release page - I release the new version binary on release page, you'd better add them to this repo's release page or that github.io site.

**Comment by hkz404** [comment]
@dreampiggy thx for your great contribution, i send you the invite email.

**Pull request merged**
